runtime: python39  # Ou a versão do Python que você está utilizando

entrypoint: gunicorn -b :$PORT app:app  # Certifique-se de que o app está sendo servido corretamente pelo Gunicorn

# Configurações de tempo limite e escalonamento
manual_scaling:
  instances: 1

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto